"use client"
import Head from 'next/head';
import Image from 'next/image';
import styles from './../../app/styles/Home.module.css';
import style from './../../app/styles/Loco.module.css'
import aboutBg from './../../public/uberbanner.jpeg'
import ceoB from './../../public/ceo.jpg'
import { FaInstagram } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";
import { FaYoutube } from "react-icons/fa";
import { motion } from 'framer-motion';
import { VelocityScroll } from './../../components/scroll'
import AOS from 'aos';
import "aos/dist/aos.css";
import { useEffect, useState } from 'react';
import Preloader from './../../components/Preloader'
import Project from './../../components/project/index';
import Modal from './../../components/model/index';
import GsapMagnetic from './../../components/gsap'
import Hero from './../../components/Hero';
import AnimCursor from './../../components/AnimCoursor';
import './../../styles/Glob.css'
export default function Home() {
	const projects = [
		{
		  title: "driving Uber",
		  src: "who.png",
		  color: "#000000"
		},
		{
		  title: "Getting diversity",
		  src: "der.png",
		  color: "#8C8C8C"
		},
		{
		  title: "integrity",
		  src: "stand.png",
		  color: "#EFE8D3"
		},
		{
		  title: "Backups MyRocks",
		  src: "back.png",
		  color: "#706D63"
		}
	  ]
	const [modal, setModal] = useState({active: false, index: 0})
	
	useEffect(() => {
		AOS.init({ duration: 2000 });
	}, []);
	
	  
	return (
		<div>
			<AnimCursor/>
			<Preloader/>

			{/* <Image className='object-cover h-48 w-96... transition-all duration-300 rounded-lg cursor-pointer filter grayscale hover:grayscale-0' src={aboutBg} /> */}
			<Hero/>
			<div className={styles.container}>
				<Head>
					<title>CreateNext App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>


				<main className={styles.main}>
					<h1 className={styles.title}>
						<VelocityScroll
							text="About Us"
							default_velocity={5}
							className="font-display text-center text-4xl font-bold tracking-[-0.02em] text-black drop-shadow-sm dark:text-white md:text-7xl md:leading-[5rem]"
						/>

					</h1>

					<p data-aos="fade-right" className={styles.description} style={{ fontWeight: "bold" }}>
						We reimagine the way the world moves for the better
					</p>

					<p data-aos="fade-right" className={styles.description}>
						Movement is what we power. It's our lifeblood. It runs through our veins. It's what gets us out of bed each morning. It pushes us to constantly reimagine how we can move better. For you. For all the places you want to go. For all the things you want to get. For all the ways you want to earn. Across the entire world. In real time. At the incredible speed of now.
					</p>
				</main>
			</div>
			<main className={style.main}>
    <div className={style.body}>
      {
        projects.map( (project, index) => {
          return <Project index={index} title={project.title} setModal={setModal} key={index}/>
        })
      }
    </div>
    <Modal modal={modal} projects={projects}/>
  </main>
			<div className={styles.row}>
				<div className={styles.imgWrapper}>
					<Image data-aos="fade-right" src={ceoB} className=' transition-all duration-300 rounded-lg cursor-pointer filter grayscale hover:grayscale-0' />

				</div>
				<div className={styles.contentWrapper}>
					<div className={styles.content}>
						<span className={styles.textWrapper}>

						</span>
						<h2 data-aos="fade-left">OUR CEO</h2>
						<p data-aos="fade-left">Movement is what we power. It's our lifeblood. It runs through our veins. It's what gets us out of bed each morning. It pushes us to constantly reimagine how we can move better. For you. For all the places you want to go. For all the things you want to get. For all the ways you want to earn. Across the entire world. In real time. At the incredible speed of now.</p>
					</div>

				</div>
			</div>

			<div className={styles.row}>
				<div className={styles.imgWrapper}>
					<Image data-aos="fade-right" src={aboutBg} className=' transition-all duration-300 rounded-lg cursor-pointer filter grayscale hover:grayscale-0' />

				</div>
				<div className={styles.contentWrapper}>
					<div className={styles.content}>
						<span className={styles.textWrapper}>

						</span>
						<h2 data-aos="fade-left">Sustainability</h2>
						<p data-aos="fade-left">Uber is committing to becoming a fully electric, zero-emission platform by 2040, with 100% of rides taking place in zero-emission vehicles, on public transit, or with micromobility. It is our responsibility as the largest mobility platform in the world to more aggressively tackle the challenge of climate change. We will do this by offering riders more ways to ride green, helping drivers go electric, making transparency a priority and partnering with NGOs and the private sector to help expedite a clean and just energy transition.</p>
					</div>

				</div>
			</div>

			<div className={styles.row}>
				<div className={styles.imgWrapper}>
					<Image data-aos="fade-right" src={aboutBg} className=' transition-all duration-300 rounded-lg cursor-pointer filter grayscale hover:grayscale-0' />

				</div>
				<div className={styles.contentWrapper}>
					<div className={styles.content}>
						<span className={styles.textWrapper}>

						</span>
						<h2 data-aos="fade-left">Rides and beyond</h2>
						<p data-aos="fade-left">In addition to helping riders find a way to go from point A to point B, we're helping people order food quickly and affordably, removing barriers to healthcare, creating new freight-booking solutions, and helping companies provide a seamless employee travel experience. And always helping drivers and couriers earn</p>
					</div>

				</div>
			</div>


			<div className="bg-black h-1/2 w-full flex md:flex-row flex-col justify-around items-start p-20">
				<div className="p-5 " data-aos="fade-right">
					<ul>
						<p className="text-white font-bold text-3xl pb-6">
							<span className="text-white">Uber</span>
						</p>
						<div className="flex gap-6 pb-5">
							<GsapMagnetic>
							<FaInstagram className="text-2xl cursor-pointer text-white hover:text-yellow-600" />
							</GsapMagnetic>
							<GsapMagnetic>
							<FaTwitter className="text-2xl cursor-pointer text-white hover:text-blue-600" />
							</GsapMagnetic>
							<GsapMagnetic>
							<FaLinkedin className="text-2xl cursor-pointer text-white hover:text-blue-600" />
							</GsapMagnetic>
							<GsapMagnetic>
							<FaYoutube className="text-2xl cursor-pointer text-white hover:text-red-600" />
							</GsapMagnetic>
						</div>
					</ul>
				</div>
				<div className="p-5" data-aos="fade-up">
					<ul>
						<p className="text-white font-bold text-2xl pb-4">Product</p>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Stocks
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Futures & Options
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Mutual Funds
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Fixed deposits
						</li>
					</ul>
				</div>
				<div className="p-5" data-aos="fade-up">
					<ul>
						<p className="text-white font-bold text-2xl pb-4">Company</p>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							About
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Products
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Pricing
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Careers
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Press & Media
						</li>
					</ul>
				</div>
				<div className="p-5" data-aos="fade-up">
					<ul>
						<p className="text-white font-bold text-2xl pb-4">Support</p>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Contact
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Support Portals
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							List Of Charges
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Downloads & Resources
						</li>
						<li className="text-white text-md pb-2 font-semibold hover:text-blue-600 cursor-pointer">
							Videos
						</li>
					</ul>
				</div>
			</div>

		</div>

	);
}