"use client"

import { Inter,Montserrat } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '../components/Header'
import SplashScreen from './../components/SplashScreen'
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'


const inter = Montserrat({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Uber Clone',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const pathname = usePathname()
  const isHome = pathname === '/'
  const [isLoading,setIsLoading] = useState(isHome)
  useEffect(() => {
    if(isLoading)
      return
  }, [isLoading])

  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        { isLoading && isHome ? (
          <SplashScreen finishLoading={() => setIsLoading(false)} /> 
        ) : (
          <>
          <Header/>
          {children}
          </>
        )}
       
        </body>
    </html>
    </ClerkProvider>
  )
}
